_home:
    path:     /
    defaults: { _controller: ACAShopBundle:Default:index }

_products:
    path: /products
    defaults: { _controller: ACAShopBundle:Products:listing }

_cart:
    path: /cart
    defaults: { _controller: ACAShopBundle:Cart:index }

_add_cart:
    path: /add_cart
    defaults: { _controller: ACAShopBundle:Cart:add }

_remove_cart:
    path: /remove_cart
    defaults: { _controller: ACAShopBundle:Cart:remove }

_update_cart:
    path: /update_cart
    defaults: { _controller: ACAShopBundle:Cart:update }

_process_order:
    path: /process_order
    defaults: { _controller: ACAShopBundle:Checkout:process }

_billing:
    path: /billing
    defaults: { _controller: ACAShopBundle:Checkout:billing }

_billing_info:
    path: /billing_info
    defaults: { _controller: ACAShopBundle:Checkout:billingInfo }

_display_receipt:
    path: /receipt
    defaults: { _controller: ACAShopBundle:Checkout:receipt }

_add_product:
    path: /add_product
    defaults: { _controller: ACAShopBundle:Product:add }

_process_login:
    path: /process_login
    defaults: { _controller: ACAShopBundle:Login:processLogin }

_process_logout:
    path: /logout
    defaults: { _controller: ACAShopBundle:Login:processLogout }
